name: Run Checks

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  run-package-checks:
    name: Run Checks on @aptos-labs/siwa
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup pnpm 10.6.4
        uses: pnpm/action-setup@v4
        with:
          version: 10.6.4

      - name: Setup Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Install Dependencies
        run: pnpm i

      - name: Run Checks
        run: pnpm check
        shell: bash

